spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/classservice}
    username: ${DB_USERNAME:classservice}
    password: ${DB_PASSWORD:classservice}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration,classpath:db/seed

logging:
  level:
    com.classservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
